package com.whf.openeyes.net.bean

/**
 * Created by whf on 2018/7/1.
 */
data class ItemData(
        val dataType: String,
        val id: Int,
        val title: String,
        val description: String,
        val library: String,
        val tags: List<Hot.Tag>,
        val consumption: Hot.Consumption,
        val resourceType: String,
        val slogan: Any,
        val provider: Hot.Provider,
        val category: String,
        val author: Hot.Author,
        val cover: Hot.Cover,
        val playUrl: String,
        val thumbPlayUrl: Any,
        val duration: Int,
        val webUrl: Hot.WebUrl,
        val releaseTime: Long,
        val playInfo: List<Any>,
        val campaign: Any,
        val waterMarks: Any,
        val adTrack: Any,
        val type: String,
        val titlePgc: String,
        val descriptionPgc: String,
        val remark: Any,
        val ifLimitVideo: Boolean,
        val searchWeight: Int,
        val idx: Int,
        val shareAdTrack: Any,
        val favoriteAdTrack: Any,
        val webAdTrack: Any,
        val date: Long,
        val promotion: Any,
        val label: Any,
        val labelList: List<Any>,
        val descriptionEditor: String,
        val collected: Boolean,
        val played: Boolean,
        val subtitles: List<Any>,
        val lastViewTime: Any,
        val playlists: Any,
        val src: Any
)